FROM ubuntu:xenial
WORKDIR /opt/chimera/bin
COPY ./run.sh ./run.sh
RUN apt-get update &&\
    apt-get install -y curl &&\
    apt-get install -y jq &&\
    mkdir /var/log/chimera &&\
    chmod +x ./run.sh &&\
    curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/cliapp --output cliapp &&\
    chmod +x cliapp

# The data folder should be shared with the webapp
ENV DATA_FOLDER=/opt/chimera/data

ENTRYPOINT ["./run.sh"]
