FROM ubuntu:xenial

WORKDIR /opt/chimera/bin

RUN apt-get update &&\
    apt-get install -y curl &&\
    apt-get clean &&\ 
    curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/webapp --output webapp &&\
    chmod +x webapp &&\
    mkdir /var/log/chimera

ENV WEBAPP_PORT=80
EXPOSE ${WEBAPP_PORT}

# The data folder should be shared with the cliapp
ENV DATA_FOLDER=/opt/chimera/data

ENTRYPOINT ["./webapp"]
